# Generated by Django 2.1.6 on 2019-02-14 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_devtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('devType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('data_type', models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('S', 'String'), ('B', 'Boolean')], default='S', max_length=1)),
                ('funct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Function')),
            ],
        ),
        migrations.CreateModel(
            name='StateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('data_type', models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('S', 'String'), ('B', 'Boolean')], default='S', max_length=1)),
                ('devType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceType')),
            ],
        ),
        migrations.CreateModel(
            name='StateAttributeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.StateAttribute')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
