# Generated by Django 2.1.6 on 2019-02-15 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_function_functionparameter_stateattribute_stateattributerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stateattributerecord',
            name='date_received',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
