# Generated by Django 2.1.6 on 2019-02-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_auto_20190215_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionparameter',
            name='data_type',
            field=models.CharField(choices=[('F', 'Float'), ('S', 'String'), ('B', 'Boolean')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='stateattribute',
            name='data_type',
            field=models.CharField(choices=[('F', 'Float'), ('S', 'String'), ('B', 'Boolean')], default='S', max_length=1),
        ),
    ]
