# Generated by Django 2.1.6 on 2019-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alerts_functionparameterconstraint_functionparameteroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionparameterconstraint',
            name='value',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
