# Generated by Django 2.1.6 on 2019-02-23 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_functionparameterconstraint_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('alert_condition', models.CharField(choices=[('>', 'Greater'), ('<', 'Smaller'), ('≠', 'Different'), ('=', 'Equal')], default='=', max_length=1)),
                ('alert_level', models.CharField(choices=[('LOW', 'Lowest'), ('MID', 'Medium'), ('HIG', 'Highest')], default='MID', max_length=3)),
                ('value', models.CharField(max_length=30)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.StateAttribute')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='alerts',
            name='device',
        ),
        migrations.DeleteModel(
            name='Alerts',
        ),
    ]
