# Generated by Django 2.1.6 on 2019-03-03 09:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_auto_20190223_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('readed', models.BooleanField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Alert')),
            ],
        ),
    ]
