# Generated by Django 2.1.6 on 2019-03-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0015_auto_20190304_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='path',
            field=models.CharField(default='/', max_length=100),
        ),
    ]
