# Generated by Django 2.1.6 on 2019-03-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_device_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Alert')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Function')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('feedbackfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.FeedbackFunction')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.FunctionParameter')),
            ],
        ),
    ]
